sequenceDiagram
  autonumber
  participant ADM as Admin
  participant I as Issuer API
  participant S as StatusList Store
  participant A as Anchor Service
  participant B as Besu SC

  ADM->>I: solicitar revogacao
  I->>S: atualizar bit na statuslist
  I->>A: publicar nova versao com hash
  A->>B: transacao de ancora
  B-->>A: confirmacao
  I-->>ADM: revogacao concluida
