sequenceDiagram
  autonumber
  participant U as Wallet
  participant GW as Gateway
  participant I as Issuer API
  participant K as Keycloak
  participant C as Custody
  participant S as StatusList Store
  participant A as Anchor Service
  participant B as Besu SC

  U->>GW: solicitar emissao
  GW->>I: requisicao de emissao
  I->>K: autenticar escopo
  K-->>I: token ok
  I->>C: assinar credencial
  C-->>I: assinatura ok
  I->>S: gravar ou atualizar statuslist
  I->>A: publicar ancora de hash e versao
  A->>B: transacao em smart contract
  B-->>A: tx confirmada
  I-->>GW: credencial emitida
  GW-->>U: credencial entregue
